### ISSUE TITLE
Not working with CM13.

### ISSUE THREAD

**Issue by krestaino** [gavinhungry/Xposed-ShowSimOperator#1]
Hey man, this seems like an awesome module. Unfortunately, it doesn't seem to be working with CM13 (13.0-20160212-NIGHTLY-bullhead). Any chance you could add support for CM?

**Comment by gavinhungry** [comment]
@krestaino,

I use CM13 myself (cm-13.0-20160214-NIGHTLY-angler), so it does work on CyanogenMod. Is it not installing, not showing you the SIM operator where you expect it, something else?

You should see your SIM operator name, which in a lot of (most?) cases is the same as your network operator string in at least the following locations: lockscreen, cellular quick settings tile and CMStats.

I changed `minSdkVersion` from Marshmallow (23) to Lollipop (22) in response to a user request - if you have v1.0.0 of this module (using API 23) installed, you may have trouble installing a new version of the module, since it's downgrading the permissions model. In that case, you'd have to uninstall the old version of the module and then install the new version.

### Background

I wonder if you're trying to use this for the same reason I am: I have a Nexus 6P on Project Fi. On the Nexus factory images, the carrier is displayed as "Fi Network," regardless of if you're on a T-Mobile tower or a Sprint tower. Of course, you can use something like [FiSwitch](https://play.google.com/store/apps/details?id=com.cheekydevs.fiswitch) to see what you're actually connected to.

On CyanogenMod, I see "Fi Network" when on T-Mobile, and "Sprint" when on ... well, Sprint. So I wrote this module so that I could see "Fi Network" all the time - but still retain statuses like "Emergency Calls Only" and "No SIM inserted."

**Comment by posydon** [comment]
Hi, Can you do for CM11?Thank you!Sorry for my english.

**Comment by gavinhungry** [comment]
Hi @posydon,

Sorry, I have no plans to support anything other than the latest version of CyanogenMod. Forks and pull requests are always welcome, however.
